spring.application.name=parking-cloud
server.port=8081

spring.rabbitmq.addresses=amqps://vdsonyrf:oIDbvFl6vArZOM2c-ZBqePKlMq83gGsB@chameleon.lmq.cloudamqp.com/vdsonyrf
spring.rabbitmq.template.default-receive-queue=parking_queue

spring.datasource.url=jdbc:mysql://avnadmin:AVNS_EHO4eyrozUgFEnV-y3b@mysql-3ccaae91-tunamoi.e.aivencloud.com:10835/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_EHO4eyrozUgFEnV-y3b
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Tu dong tao bang tu code Javaaaaa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#Ket noi MongoDB
# Link ket noi MongoDB Atlas chung cho ca 5 may
spring.data.mongodb.uri=mongodb+srv://nguyennguyen672004_db_user:zTfx4Z61liC2pJ9A@cluster0.7rhennq.mongodb.net/park_cloud?appName=Cluster0

# Ten cong
server.gate.name=GATE_ANH