spring.application.name=parking-cloud
server.port=8081

spring.rabbitmq.addresses=amqps://vdsonyrf:oIDbvFl6vArZOM2c-ZBqePKlMq83gGsB@chameleon.lmq.cloudamqp.com/vdsonyrf
spring.rabbitmq.template.default-receive-queue=parking_queue

spring.datasource.url=jdbc:mysql://localhost:3306/baidoxe?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Tuananhqp2005@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# T? ??ng t?o b?ng t? code Javaaaaa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#Ket noi MongoDB
# Link k?t n?i MongoDB Atlas chung cho c? 5 máy
spring.data.mongodb.uri=mongodb+srv://nguyennguyen672004_db_user:zTfx4Z61liC2pJ9A@cluster0.7rhennq.mongodb.net/park_cloud?appName=Cluster0

# Ten cong
server.gate.name=GATE_ANH